# Generated by Django 4.1.7 on 2023-03-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.DO_NOTHING, to='payapp.currency'),
        ),
    ]
