# Generated by Django 4.1.7 on 2023-03-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_type', models.CharField(choices=[('USD', 'Dollar'), ('GBP', 'Pound'), ('EUR', 'Euro')], default='GBP', max_length=3, primary_key=True, serialize=False)),
                ('symbol', models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro')], default='£', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.DO_NOTHING, to='register.currency'),
        ),
    ]
