# Generated by Django 4.1.7 on 2023-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_currency_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
    ]
