# Generated by Django 4.1.7 on 2023-04-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('currency_from', models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='register.currency')),
                ('currency_to', models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='register.currency')),
            ],
        ),
    ]
