# Generated by Django 4.1.7 on 2023-03-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('USD', 'Dollar'), ('GBP', 'Pound'), ('EUR', 'Euro')], default='GBP', max_length=3)),
                ('symbol', models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro')], default='£', max_length=2)),
            ],
        ),
    ]
