# Generated by Django 4.1.7 on 2023-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_type', models.CharField(choices=[('USD', 'Dollar'), ('GBP', 'Pound'), ('EUR', 'Euro')], default='GBP', max_length=3, primary_key=True, serialize=False)),
                ('symbol', models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro')], default='£', max_length=1)),
            ],
        ),
    ]
