# Generated by Django 4.1.7 on 2023-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('GBP', 'Pound'), ('EUR', 'Euro')], default='GBP', max_length=3, primary_key=True, serialize=False),
        ),
    ]
