# Generated by Django 4.1.7 on 2023-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_remove_currency_id_alter_currency_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro')], default='£', max_length=1),
        ),
    ]
